language: objective-c  #1
<<<<<<< HEAD
osx_image: xcode7.0 #2
xcode_project: MovingHelper.xcproject #3
xcode_scheme: MovingHelper #4
xcode_sdk: iphonesimulator8.4 #5
=======
osx_image: xcode7 #2
xcode_project: ./MovingHelper/MovingHelper.xcodeproj #3
xcode_scheme: MovingHelper #4
xcode_sdk: iphonesimulator9.0 #5
>>>>>>> master
