language: objective-c  #1
osx_image: xcode7 #2

### If you want to specify just the basic inputs to a single project to Travis, do so like this.
#xcode_project: ./MovingHelper/MovingHelper.xcodeproj #3
#xcode_scheme: MovingHelper #4
#xcode_sdk: iphonesimulator9.0 #5

### For running script, do this:
script:
  - echo staring build and test...
  - xctool -project ./MovingHelper/MovingHelper.xcodeproj -scheme MovingHelper -sdk iphonesimulator9.0 build test

